#a=int(input("a oldal:"))
#b=int(input("b oldal:"))
#c=int(input("Fordulási szög:"))
import turtle
ablak = turtle.Screen()
Sanyi = turtle.Turtle()
ablak.bgcolor("white")
ablak.title("Hello, Eszti!")
Eszti = turtle.Turtle()
Eszti.color("blue")
Eszti.pensize(3)
Eszti.forward(50)
Eszti.left(120)
Eszti.forward(50)
Sanyi.shape("turtle")
Sanyi.pensize(3)
Sanyi.forward(90)
Sanyi.left(90)
Sanyi.forward(90)
Sanyi.left(90)
Sanyi.forward(90)
Sanyi.left(90)
Sanyi.forward(90)
Sanyi.left(90)
Sanyi.forward(90)
Sanyi.left(90)
Sanyi.forward(90)
Sanyi.right(90)
Sanyi.forward(200)
Sanyi.forward(90)
Sanyi.right(90)
Sanyi.forward(90)
Sanyi.right(90)
Sanyi.forward(90)
Sanyi.right(90)
Sanyi.forward(90)
Sanyi.right(90)
Sanyi.forward(90)
Sanyi.forward(90)
Sanyi.left(90)
Sanyi.forward(50)
Sanyi.left(45)
Sanyi.forward(150)
Sanyi.left(45)
Sanyi.forward(375)
Sanyi.left(45)
Sanyi.forward(150)
Sanyi.left(45)
Sanyi.forward(50)
Sanyi.left(90)
Sanyi.forward(150)
ablak.mainloop()