a=input("Milyen színű legyen a háttér?")
import turtle
ablak = turtle.Screen()
ablak.bgcolor("a")
Sanyi = turtle.Turtle()
Sanyi.forward(50)
Sanyi.left(90)
Sanyi.forward(30)
Eszti = turtle.Turtle()
b=input("Milyen színű legyen Eszti?")
c=int(input("Mennyi legyen a toll vastagsága?"))
Eszti.pensize(c)
Eszti.color("b")
ablak.mainloop()